name: release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: write
  packages: write

jobs:
  release-tag:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Install tools via asdf
        uses: asdf-vm/actions/install@v2.1.0

      - name: Release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
